### ISSUE TITLE
not able to set up reset

### ISSUE THREAD

**Issue by rupalitanna0** [rupalitanna0/blackjack#3]
i tried but my code doesnt work after that
and my stand is not working

**Comment by pavankat** [comment]
hey Rupali I don't see anything here except "i tried but my code doesnt work after that
and my stand is not working". I need a lot more info

**Comment by pavankat** [comment]
tell me what you tried to fix it, give me the code that's breaking, tell me why you think it's breaking

**Comment by rupalitanna0** [comment]
oh sorry
will just send it to u

**Comment by rupalitanna0** [comment]
var Dealer = function (){
	this.hand = new Hands();
	this.deck = new DeckCard();
	this.deal = function  () {
		return this.deck.getRandom();
	}
	this.hit = function(){
		return this.hand.hit();
	}
}

i was trying to put the reset it in here
startGame: function  () {
		console.log('game started');
		this.dealer.deck.createDeck();
		this.dealer.deal();
		var moneyDisplay = document.getElementById("moneyofplayer");
		moneyDisplay.innerHTML = (this.player.playermoney);
		
		

	},
and in this

**Comment by rupalitanna0** [comment]
i tried it but then deleted it as i wasnt sure what was going on
couldnt fig out anythg

**Comment by rupalitanna0** [comment]
solved

**Comment by rupalitanna0** [comment]
my images are not working
